# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        node-version: '12.x'
        cache: 'npm'
        cache-dependency-path: client/yarn.lock
    - name: Install dependencies
      run: yarn install 
      working-directory: client
    - name: Run tests
      run: yarn run test
      working-directory: client
    - uses: actions/checkout@v1
      with:
        node-version: '12.x'
        cache: 'npm'
        cache-dependency-path: server/yarn.lock
    - name: Install dependencies
      run: yarn install 
      working-directory: server
    - name: Run tests
      run: yarn run test
      working-directory: server
